aliases: # ProductID (Found under 'Settings'->'Equipment' on www.picobrew.com) mapping to friendly nickname
  Zymatic:
    #ProductID : Nickname
  ZSeries:
    #ProductID : Nickname
  PicoBrew:
    #ProductID : Nickname
  PicoFerm:
    #ProductID : Nickname
  PicoStill:
    #ProductID : Nickname

firmware: # specify minimum firmware versions to push to your devices (binaries found in ./app/firmware/<device_type>/)
  # ZSeries: 0.0.119
  # PicoBrew: 0.1.34
  # PicoStill: 0.0.35